workspace(name = "example_upgradable_github_archive_constrained")

local_repository(
    name = "bazel_upgradable",
    path = "..",
)

load("@bazel_upgradable//:rule.bzl", "upgradable_repository")

upgradable_repository(
    name = "bazel_skylib",
    remote = "https://github.com/bazelbuild/bazel-skylib.git",
    tag = "~1",
)

load("@bazel_skylib//lib:versions.bzl", "versions")

# Not an actual requirement. This is only to demonstrate usage of upgradable_repository
versions.check(minimum_bazel_version = "0.19")
