workspace(name = "example_upgradable_github_archive_constrained")

local_repository(
    name = "bazel_upgradable",
    path = "..",
)

load("@bazel_upgradable//rules:github.bzl", "upgradable_github_archive")

upgradable_github_archive(
    name = "bazel_skylib",
    slug = "bazelbuild/bazel-skylib",
    tag = "~=0.8",
)

load("@bazel_skylib//lib:versions.bzl", "versions")

# Not an actual requirement. This is only to demonstrate usage of upgradable_github_archive
versions.check(minimum_bazel_version = "0.19")
