on: push
name: Tests
env:
  BAZEL: bazelisk
  BAZELISK_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test_on_macos:
    name: RUN TESTS ON macos
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./test.sh
  test_on_ubuntu:
    name: RUN TESTS ON ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./test.sh
  test_on_windows:
    name: RUN TESTS ON windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: ./test.sh
      shell: bash
